name = "LegendGeSim"
uuid = "e592b54b-af3c-468f-bcc7-10a913e293a7"
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
EncodedArrays = "97725368-735e-11e9-0dd7-6bf34c3b13a8"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LegendDataTypes = "99e09c13-5545-5ee2-bfa2-77f358fb75d8"
LegendHDF5IO = "c9265ca6-b027-5446-b1a4-febfa8dd10b0"
LegendTextIO = "c397c909-374d-579b-8af3-fa3aa4f02e89"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MJDSigGen = "0b925020-e659-485c-98dd-189633cb4be4"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PropDicts = "4dc08600-4268-439e-8673-d706fafbb426"
RadiationDetectorDSP = "afd6e06f-c550-5763-af36-7391d39e46ec"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
RadiationSpectra = "4f207c7e-01da-51d7-a1a0-c8c06dd1d883"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ArgCheck = "2"
ArraysOfArrays = "0.5"
Clustering = "0.14"
CurveFit = "0.3"
DSP = "0.7"
Distributions = "0.25"
ElasticArrays = "1"
EncodedArrays = "0.2"
FillArrays = "0.12"
HDF5 = "0.15"
IntervalSets = "0.5"
JSON = "0.21"
LegendDataTypes = "0"
LegendHDF5IO = "0"
LegendTextIO = "0"
LsqFit = "0.12"
MJDSigGen = "0.1"
Parameters = "0.12"
Polynomials = "2"
PropDicts = "0.2"
RadiationDetectorDSP = "0.1"
RadiationDetectorSignals = "0.1"
RadiationSpectra = "0.5"
Random123 = "1.4"
RecipesBase = "1.2"
Requires = "1.1"
SolidStateDetectors = "0.7"
StaticArrays = "1.2"
StatsBase = ""0.33
StructArrays = "0.6"
Tables = "1.6"
TypedTables = "1.4"
Unitful = "1.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
